### ISSUE TITLE
Broken link en accesorio HUB USB C (8 en 1)

### ISSUE THREAD

**Issue by uRuiz** [baumannzone/baumannzone.dev#169]
Leyendo los detalles de tu setup he visto que hay un link roto en el adaptador [HUB USB C (8 en 1)](https://github.com/baumannzone/baumannzone.dev/blob/main/components/UsesPage/uses.md)
Supongo que lo habrán quitando de Amazon. Por si quieres cambiar el link 😊

**Comment by baumannzone** [comment]
¡Gracias @uRuiz! Acabo de verlo. He actualizado la pag, ¡gracias!

**Comment by baumannzone** [comment]
Please @all-contributors add @uRuiz for bug
