### ISSUE TITLE
relative path error

### ISSUE THREAD

**Issue by eliutdev** [baumannzone/baumannzone.dev#206]
[Estaba empezando a experimentar con los live coding de `CSS-art` en [Twitch](twitch.tv/baumannzone).](https://github.com/baumannzone/baumannzone.dev/blob/2770f853019483ae9ef253a4537e4fe2ba263b30/content/blog/pure-css-cake.md?plain=1#L16)

**Comment by baumannzone** [comment]
Oh! Gracias por reportar el error. Ahora mismo lo soluciono!

**Comment by baumannzone** [comment]
please @all-contributors add @eliutdev for bugs

**Comment by eliutdev** [comment]
> Oh! Gracias por reportar el error. Ahora mismo lo soluciono!

De nada!
