### ISSUE TITLE
Add tiktok to the profile component and the footer component

### ISSUE THREAD

**Issue by baumannzone** [baumannzone/baumannzone.dev#309]
Use https://simpleicons.org/?q=tikt to get the icon.

My tt profile is: https://www.tiktok.com/@baumannzone

**Comment by SarveshPatil29** [comment]
Hi! I would like to work on this issue. Can you please assign it to me?

**Comment by baumannzone** [comment]
Yes. Will do asap.

**Comment by baumannzone** [comment]
Closed, see #311
