### ISSUE TITLE
Comillas simples en lugar de comillas invertidas

### ISSUE THREAD

**Issue by rr69sport** [baumannzone/baumannzone.dev#383]
En el componente **ArticleCard.astro**, línea 66 en el preview de GitHub, el link de la etiqueta `a` está entre comillas simples y no dentro de comillas invertidas.

Enlace del componente **ArticleCard.astro**: https://github.com/baumannzone/baumannzone.dev/blob/main/src/components/ArticleCard.astro#L66

![template-string-as-string](https://github.com/baumannzone/baumannzone.dev/assets/59400168/bad9f57a-4dc1-44c1-bcfb-ab68b6e76dd6)

**Comment by baumannzone** [comment]
Gracias!

**Comment by baumannzone** [comment]
Please @allcontributors add @rr69sport for bug

**Comment by baumannzone** [comment]
Fixed, thanks!
