### ISSUE TITLE
Título oscuro en modo oscuro

### ISSUE THREAD

**Issue by rr69sport** [baumannzone/baumannzone.dev#384]
En los posts, si estás en modo oscuro, los títulos se ven en color oscuro en base a una clase de tailwind llamada `text-gray-900`

Enlace a **BlogPostLayout.astro - Línea 33**: https://github.com/baumannzone/baumannzone.dev/blob/main/src/layouts/BlogPostLayout.astro#L33

![dark-title-on-dark-mode](https://github.com/baumannzone/baumannzone.dev/assets/59400168/0eab03d6-157b-4739-86eb-ad1f58310503)

**Comment by baumannzone** [comment]
Gracias! Tengo el dark mode a medias todavía 😅

**Comment by rr69sport** [comment]
> Gracias! Tengo el dark mode a medias todavía 😅

Suele pasar 😅

**Comment by baumannzone** [comment]
please @allcontributors add @rr69sport for bug

**Comment by baumannzone** [comment]
Fixed, thanks!
