### ISSUE TITLE
Responsive issue in the footer

### ISSUE THREAD

**Issue by HorusGoul** [baumannzone/baumannzone.dev#51]
When I reached the footer of the site I noticed that the LinkedIn icon is in a new line. I don't know if this is intentional but it also provokes a difference in the spacing around that section of the footer, which makes it look weird.

**Device info that may be useful for testing:**
Device width in css pixels: **412px**

**Screenshot:**
![Screenshot_20210730-155937](https://user-images.githubusercontent.com/6759612/127664499-d535124e-920f-405f-bb79-b1fa34062a01.jpg)

P.S. The site looks awesome, congrats on the release!

**Comment by baumannzone** [comment]
Please @all-contributors add @HorusGoul for bugs

**Comment by kevinjuanjacque** [comment]
@HorusGoul 
this pr fixes this issue 

[FIX fotter responsive](https://github.com/baumannzone/baumannzone.dev/pull/287)
